/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualTryonRouteImport } from './routes/virtual-tryon'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StonesRouteImport } from './routes/stones'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MetalsRouteImport } from './routes/metals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VirtualTryonRoute = VirtualTryonRouteImport.update({
  id: '/virtual-tryon',
  path: '/virtual-tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StonesRoute = StonesRouteImport.update({
  id: '/stones',
  path: '/stones',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalsRoute = MetalsRouteImport.update({
  id: '/metals',
  path: '/metals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/metals': typeof MetalsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stones': typeof StonesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/try-on': typeof TryOnRoute
  '/virtual-tryon': typeof VirtualTryonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/metals': typeof MetalsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stones': typeof StonesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/try-on': typeof TryOnRoute
  '/virtual-tryon': typeof VirtualTryonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/metals': typeof MetalsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stones': typeof StonesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/try-on': typeof TryOnRoute
  '/virtual-tryon': typeof VirtualTryonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/design'
    | '/inventory'
    | '/login'
    | '/metals'
    | '/privacy'
    | '/process'
    | '/products'
    | '/purchases'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shop'
    | '/stones'
    | '/suppliers'
    | '/terms'
    | '/try-on'
    | '/virtual-tryon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/design'
    | '/inventory'
    | '/login'
    | '/metals'
    | '/privacy'
    | '/process'
    | '/products'
    | '/purchases'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shop'
    | '/stones'
    | '/suppliers'
    | '/terms'
    | '/try-on'
    | '/virtual-tryon'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/design'
    | '/inventory'
    | '/login'
    | '/metals'
    | '/privacy'
    | '/process'
    | '/products'
    | '/purchases'
    | '/rates'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shop'
    | '/stones'
    | '/suppliers'
    | '/terms'
    | '/try-on'
    | '/virtual-tryon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MetalsRoute: typeof MetalsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  RatesRoute: typeof RatesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StonesRoute: typeof StonesRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  TryOnRoute: typeof TryOnRoute
  VirtualTryonRoute: typeof VirtualTryonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-tryon': {
      id: '/virtual-tryon'
      path: '/virtual-tryon'
      fullPath: '/virtual-tryon'
      preLoaderRoute: typeof VirtualTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stones': {
      id: '/stones'
      path: '/stones'
      fullPath: '/stones'
      preLoaderRoute: typeof StonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metals': {
      id: '/metals'
      path: '/metals'
      fullPath: '/metals'
      preLoaderRoute: typeof MetalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MetalsRoute: MetalsRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  RatesRoute: RatesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StonesRoute: StonesRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  TryOnRoute: TryOnRoute,
  VirtualTryonRoute: VirtualTryonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
