import { PublicFooter } from "@/components/public-footer";
import { PublicNav } from "@/components/public-nav";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
	component: PrivacyPage,
});

const sections = [
	{
		title: "1. Information We Collect",
		body: `We collect information you provide directly when you register for an account (name, email address, business name), information generated by your use of the Service (products, customers, suppliers, sales transactions, inventory records), technical data automatically collected when you access the Service (IP address, browser type, device identifiers, session tokens), and communications you send to us.`,
	},
	{
		title: "2. How We Use Your Information",
		body: `We use the information we collect to provide, maintain, and improve the Service; to process transactions and generate invoices and reports; to authenticate your identity and secure your account; to send you service-related communications including account verification, security alerts, and support messages; to analyse usage patterns and improve the user experience; and to comply with legal obligations under applicable Nepali and international law.`,
	},
	{
		title: "3. Business Data",
		body: `All business data you enter into the Service — including product catalogues, customer records, supplier information, and transaction history — remains your property at all times. We do not sell, trade, or rent your business data to third parties. We access your data only to provide the Service, troubleshoot technical issues, or as required by law. We maintain strict internal controls to limit access to your data to authorised personnel.`,
	},
	{
		title: "4. Data Storage & Security",
		body: `Your data is stored on servers located in secure, access-controlled data centres. We implement industry-standard security measures including TLS encryption for data in transit, encryption at rest for sensitive fields, role-based access controls within your account, session management with automatic expiry, and audit logging of access and changes. No method of electronic transmission or storage is 100% secure; we cannot guarantee absolute security, but we maintain commercially reasonable safeguards.`,
	},
	{
		title: "5. Cookies & Tracking",
		body: `We use session cookies necessary for authentication and to maintain your login state. We do not use third-party advertising cookies. Analytics data (page views, feature usage) is collected using privacy-respecting, first-party analytics to understand how the Service is used and to guide product improvements. You can control cookie settings through your browser, though disabling session cookies will prevent you from logging in.`,
	},
	{
		title: "6. Data Sharing",
		body: `We do not sell or rent your personal information or business data. We may share information with trusted service providers who help us operate the Service (hosting providers, email delivery services) under strict confidentiality agreements. We may disclose information if required by law, court order, or government authority. In the event of a business merger or acquisition, user data may be transferred subject to the same privacy commitments.`,
	},
	{
		title: "7. Metal Rate Data",
		body: `Rate data displayed in the Service (global spot prices, Nepal NGSDA rates) may be sourced from third-party data providers. Use of such data is subject to the providers' own terms and conditions. We do not store personally identifiable data in connection with rate lookups.`,
	},
	{
		title: "8. Your Rights",
		body: `You have the right to access the personal information we hold about you; to request correction of inaccurate information; to request deletion of your account and associated personal data (note: anonymised aggregate data may be retained); to export your business data in a machine-readable format; and to withdraw consent for optional data processing. To exercise these rights, contact us through the account portal.`,
	},
	{
		title: "9. Data Retention",
		body: `We retain your account information and business data for as long as your account is active. If you close your account, you may request a data export within 30 days. After the export window, your personal identifiers are deleted. Transaction records may be retained in anonymised form to comply with Nepali tax and accounting regulations.`,
	},
	{
		title: "10. Children's Privacy",
		body: `The Service is intended for business use and is not directed to children under 18. We do not knowingly collect personal information from children. If you believe we have inadvertently collected information from a minor, please contact us immediately.`,
	},
	{
		title: "11. Changes to This Policy",
		body: `We may update this Privacy Policy from time to time. We will notify you of material changes by email or through an in-app notice. Your continued use of the Service after changes are posted constitutes your acceptance of the updated policy.`,
	},
	{
		title: "12. Contact",
		body: `If you have questions or concerns about this Privacy Policy or our data practices, please contact our data team through the account portal. We respond to all privacy inquiries within 5 business days.`,
	},
];

function PrivacyPage() {
	const updated = "1 May 2026";

	return (
		<div className="min-h-screen bg-[#FAFAF8] text-[#0D0D0B] dark:bg-[#0C0C0A] dark:text-[#F0F0EB]">
			<PublicNav />

			<main className="mx-auto max-w-3xl px-6 pb-24 pt-40">
				<p className="mb-4 text-[10px] tracking-[0.22em] uppercase text-[#C4A84F]">Legal</p>
				<h1 className="mb-3 text-[38px] font-light leading-[1.1] tracking-[-0.02em]">
					Privacy Policy
				</h1>
				<p className="mb-6 text-[12px] text-[#ADADAA]">Last updated: {updated}</p>

				<div className="mb-12 rounded-xl border border-[#C4A84F]/25 bg-[#C4A84F]/5 p-5">
					<p className="text-[13px] leading-relaxed text-[#6B6B67] dark:text-[#888882]">
						<span className="font-medium text-[#C4A84F]">In plain terms:</span>{" "}
						Your business data belongs to you. We don't sell it. We use it only to run the Service. You can export or delete it at any time.
					</p>
				</div>

				<div className="space-y-0 divide-y divide-[#E8E8E3] dark:divide-[#1E1E1C]">
					{sections.map((s) => (
						<div key={s.title} className="py-8">
							<h2 className="mb-3 text-[15px] font-medium">{s.title}</h2>
							<p className="text-[13px] leading-[1.8] text-[#6B6B67] dark:text-[#888882]">{s.body}</p>
						</div>
					))}
				</div>
			</main>

			<PublicFooter />
		</div>
	);
}
